apiVersion: v1 # API version of Kubernetes resource
kind: Pod # Kubernetes resource name
metadata: # Metadatas e.g., name, namespace, labels, annotations
  name: counter
spec: # Main part: Disired states of resource
  containers:
  - name: count # Name of container
    image: busybox # Image of container
    args: [
      /bin/sh,
      -c,
      'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done'
    ] # Args of entrypoint in image